### ISSUE TITLE
Komponente Deck bauen

### ISSUE THREAD

**Issue by andreasbonke** [vyvytn/avt#10]
# User Stories

## 15. Als DJ will ich schnell in der Playlist vor und zurück gehen
- [x] skip button geht vorwärts #12 
- [x] previous button geht rückwärts #12 
- [x] bei skip auf dem letzten Song wird zum ersten in der Playlist gesprungen #12 
- [x] bei prev auf dem ersten Song wird zum letzten Song der Playlist gesprungen #12 

## 16. Als DJ will ich einen Track pausieren können.
- [x] Playback kann pausiert und an gleicher Stelle incl. Filter/Speed etc. vorgesetzt werden #12 

## 17. Als DJ will ich einen Track stoppen können.
- [x] Playback kann auf Start zurückgesetzt werden #12 
- [x] Filter/Speed werden auch zurückgesetzt #12
