### ISSUE TITLE
Komponente Master Control bauen

### ISSUE THREAD

**Issue by andreasbonke** [vyvytn/avt#11]
# User Stories

## 18. Als DJ will ich das Tempo eines Decks ändern können.
- [ ] Tempo wird beim Ändern des Songs zurückgesetzt #12 
- [ ] Am Temporegler sind 1, 1.25, 1.5, 0.75, 0.5, etc. markiert 
- [ ] BPM kriegt man aus einem Song nicht raus (schwierig)
- [ ] (maybe) Temporegler rastet bei 1 ein #12 

## 21. Als DJ will ich den Abspielfokus smooth von einem Deck auf das andere wechseln können.
- [x] Crossfader schaft smoothen Übergang #12 
- [ ] Paused/stopped song starts once faded in #12 
- [ ] Es sind 0.5, 0.75, 0.25, etc markiert (ohne numerische Werte)

## 22. Als DJ will ich die Lautstärke separat einstellen können, um möglich lauten/leisen einzelner Tracks auszugeleichen.
- [ ] Es sind 1, 0.75, 0.5, 0.25, etc markiert
- [ ] Die Lautstärke des einen Decks beeinflusst die des anderen nicht #12 

## 23. Als DJ will ich die gesamt Lautstärke einstellen können.
- [ ] Es sind 1, 0.75, 0.5, 0.25, etc markiert
- [ ] Die Lautstärken der einzelen Decks werden nicht verändert #12
