### ISSUE TITLE
Komponente Effekte/Filter bauen

### ISSUE THREAD

**Issue by Inv1ctus** [vyvytn/avt#13]
# User Stories

## 19. Als DJ will ich einem Deck eine Effekt hinzufügen können.
- [x] Effekte/Filter werden gelistet #1 
- [x] Hinzufügen eines Effekts hat den gewünschten Effekt #12
- [x] Aktive Efekte werden hervorgehoben ODER hinterlegt

## 20. Als DJ will ich einen aktiven Effekt wieder entfernen können.
- [x] Deaktivierung des Effekts #12
- [x] Effekt wird nicht mehr hervorgehoben
