### ISSUE TITLE
show metadata of a song

### ISSUE THREAD

**Issue by vyvytn** [vyvytn/avt#34]
## 11. Als DJ will ich wissen welcher Song gerade abgespielt wird.
- [x] relevante Meta Daten (wenn vorhanden) werden aus hochgeladenen Dateien extrahiert #12 
- [x] Wenn keine Meta Daten vorhanden wird der Dateiname ohne Endung verwendet #12 
- [x] zugehörige Meta Daten werden aus APIs gezogen (wenn Track aus API) #12 
- [x] aus den zur Verfügung stehenden Daten wird etwas sinnvolles angezeigt #1
