### ISSUE TITLE
change playlist: edit, remove, order

### ISSUE THREAD

**Issue by vyvytn** [vyvytn/avt#37]
## 6. Als Uploader will ich einer Playlist einen Song zuweisen.

- [x] Drag & Drop aus der Bibliothek #1 
- [x] Es wird graphisch hervorgehoben wohin gedraggt werden kann #1 
- [x] Duplikate werden abgewiesen
- [x] Songs in der Playlist vom player abspielbar

## 7. Als Uploader will ich sehen ob ein Song einer Playlist angehört.

- [NO ] Hinzugefügte sind farbig hinterlegt

## 8. Als Uploader will ich eine Songs aus einer Playlist entfernen, um diese
übersichtlicher zu machen.

- [x] Entfernte Songs sind nicht mehr verfügbar
- [x] Entfernte Songs sind in der Bibliothek nicht farblich hinterlegt

## 9. Als Uploader will ich die Reihenfolge einer Playlist verändern können.

- [x] Drag & Drop der Songs ist möglich #1
